import Phaser from 'phaser'; import { FONT,hex } from '../ui/theme'; import type { GameThemeConfig } from '../data/themes'; import type { Grid } from './SudokuSolver';
export type CompletedUnit=`row-${number}`|`col-${number}`|`box-${number}`;
export class SudokuBoard extends Phaser.GameObjects.Container {
  values:Grid;notes:number[][][];private given:boolean[][];private cells:Phaser.GameObjects.Rectangle[][]=[];private texts:Phaser.GameObjects.Text[][]=[];private noteTexts:Phaser.GameObjects.Text[][][]=[];private theme:GameThemeConfig;private wrongCells:Array<{row:number;col:number}>=[];selected={row:-1,col:-1};onSelect?:(r:number,c:number)=>void;readonly size=378;readonly cell=42;
  constructor(scene:Phaser.Scene,x:number,y:number,puzzle:Grid,theme:GameThemeConfig){super(scene,x,y);scene.add.existing(this);this.theme=theme;this.values=puzzle.map(r=>[...r]);this.given=puzzle.map(r=>r.map(v=>v!==0));this.notes=Array.from({length:9},()=>Array.from({length:9},()=>[]));this.add(scene.add.rectangle(0,0,this.size,this.size,theme.board).setOrigin(0));
    const noteSlot=this.cell/3;
    for(let r=0;r<9;r++){this.cells[r]=[];this.texts[r]=[];this.noteTexts[r]=[];for(let c=0;c<9;c++){const box=scene.add.rectangle(c*this.cell,r*this.cell,this.cell,this.cell,theme.board,0).setOrigin(0).setInteractive({useHandCursor:true});box.on('pointerup',()=>{this.select(r,c);this.onSelect?.(r,c);});this.add(box);this.cells[r][c]=box;const text=scene.add.text(c*this.cell+this.cell/2,r*this.cell+this.cell/2,'',{fontFamily:FONT,fontSize:'24px',fontStyle:this.given[r][c]?'bold':'normal',color:hex(theme.givenNumber),align:'center'}).setOrigin(.5);this.add(text);this.texts[r][c]=text;this.noteTexts[r][c]=Array.from({length:9},(_,index)=>{const note=index+1,noteCol=index%3,noteRow=Math.floor(index/3),noteText=scene.add.text(c*this.cell+(noteCol+.5)*noteSlot,r*this.cell+(noteRow+.5)*noteSlot,String(note),{fontFamily:FONT,fontSize:'9px',color:hex(theme.noteNumber),align:'center'}).setOrigin(.5).setVisible(false);this.add(noteText);return noteText;});}}
    const grid=scene.add.graphics();for(let i=0;i<=9;i++){grid.lineStyle(i%3===0?2.5:1,i%3===0?theme.gridStrong:theme.grid,i%3===0 ? .9 : .75);grid.lineBetween(i*this.cell,0,i*this.cell,this.size);grid.lineBetween(0,i*this.cell,this.size,i*this.cell);}this.add(grid);this.refresh();
  }
  isGiven(r:number,c:number){return this.given[r][c];}
  select(r:number,c:number){this.selected={row:r,col:c};this.wrongCells=[];this.refresh();}
  setValue(r:number,c:number,value:number,wrong=false){this.values[r][c]=value;this.notes[r][c]=[];this.wrongCells=wrong?this.findConflicts(r,c,value):[];if(wrong&&!this.wrongCells.some(cell=>cell.row===r&&cell.col===c))this.wrongCells.push({row:r,col:c});this.refresh();}
  clearWrong(){this.wrongCells=[];this.refresh();}
  setNotes(r:number,c:number,notes:number[]){this.notes[r][c]=notes;this.values[r][c]=0;this.refresh();}
  refresh(){const sr=this.selected.row,sc=this.selected.col,selectedValue=sr>=0?this.values[sr][sc]:0;for(let r=0;r<9;r++)for(let c=0;c<9;c++){const wrong=this.wrongCells.some(cell=>cell.row===r&&cell.col===c);let color=this.theme.board,alpha=0;if(wrong){color=this.theme.danger;alpha=.22;}else if(r===sr&&c===sc){color=this.theme.selected;alpha=1;}else if(selectedValue&&this.values[r][c]===selectedValue){color=this.theme.sameNumber;alpha=1;}else if(sr>=0&&(r===sr||c===sc||this.boxIndex(r,c)===this.boxIndex(sr,sc))){color=this.theme.peer;alpha=1;}this.cells[r][c].setFillStyle(color,alpha);const value=this.values[r][c],notes=this.notes[r][c];this.texts[r][c].setText(value?String(value):'').setFontSize(24).setFontStyle(value&&this.given[r][c]?'bold':'normal').setColor(wrong?hex(this.theme.danger):this.given[r][c]?hex(this.theme.givenNumber):hex(this.theme.playerNumber));for(let index=0;index<9;index++)this.noteTexts[r][c][index].setVisible(!value&&notes.includes(index+1)).setColor(hex(this.theme.noteNumber));}}
  animateValue(r:number,c:number){const text=this.texts[r][c];this.scene.tweens.add({targets:text,scale:{from:.8,to:1},duration:150,ease:'Back.easeOut'});}
  shakeCell(r:number,c:number){const cell=this.cells[r][c],text=this.texts[r][c],baseX=c*this.cell,textX=c*this.cell+21;this.scene.tweens.add({targets:[cell,text],x:'+=5',duration:45,yoyo:true,repeat:2,onComplete:()=>{cell.x=baseX;text.x=textX;}});}
  getCompletedUnits():Set<CompletedUnit>{const units=new Set<CompletedUnit>();for(let i=0;i<9;i++){if(this.values[i].every(Boolean))units.add(`row-${i}`);if(this.values.every(row=>row[i]!==0))units.add(`col-${i}`);}for(let box=0;box<9;box++){const br=Math.floor(box/3)*3,bc=(box%3)*3;let complete=true;for(let r=br;r<br+3;r++)for(let c=bc;c<bc+3;c++)if(!this.values[r][c])complete=false;if(complete)units.add(`box-${box}`);}return units;}
  flashUnits(units:CompletedUnit[]){for(const unit of units){const [type,indexText]=unit.split('-'),index=Number(indexText),targets:Phaser.GameObjects.Rectangle[]=[];if(type==='row')targets.push(...this.cells[index]);else if(type==='col')for(let r=0;r<9;r++)targets.push(this.cells[r][index]);else{const br=Math.floor(index/3)*3,bc=(index%3)*3;for(let r=br;r<br+3;r++)for(let c=bc;c<bc+3;c++)targets.push(this.cells[r][c]);}targets.forEach(cell=>{cell.setFillStyle(this.theme.accent,.2);this.scene.tweens.add({targets:cell,alpha:{from:.55,to:1},duration:240,yoyo:true,onComplete:()=>this.refresh()});});}}
  countValue(value:number){return this.values.reduce((count,row)=>count+row.filter(item=>item===value).length,0);}
  setInputEnabled(enabled:boolean){for(const row of this.cells)for(const cell of row){cell.disableInteractive();if(enabled)cell.setInteractive({useHandCursor:true});}}
  isComplete(){return this.values.every(row=>row.every(value=>value!==0));}
  private findConflicts(row:number,col:number,value:number){if(!value)return[];const conflicts:Array<{row:number;col:number}>=[];for(let i=0;i<9;i++){if(i!==col&&this.values[row][i]===value)conflicts.push({row,col:i});if(i!==row&&this.values[i][col]===value)conflicts.push({row:i,col});}const br=Math.floor(row/3)*3,bc=Math.floor(col/3)*3;for(let r=br;r<br+3;r++)for(let c=bc;c<bc+3;c++)if((r!==row||c!==col)&&this.values[r][c]===value&&!conflicts.some(item=>item.row===r&&item.col===c))conflicts.push({row:r,col:c});return conflicts;}
  private boxIndex(r:number,c:number){return Math.floor(r/3)*3+Math.floor(c/3);}
}
