import type { PlayerData,Difficulty,SkillLevel,LevelMode,RewardSnapshot } from '../types'; import { RewardSystem } from './RewardSystem'; import { AchievementSystem } from './AchievementSystem'; import { LevelManager } from './LevelManager'; import { TitleManager } from './TitleManager'; import { ShopManager } from './ShopManager';
const KEY='sudoku-planet-player-v1';const defaults=():PlayerData=>({level:1,experience:0,coins:100,completedGames:0,bestTime:{},streakDays:1,achievements:[],history:[],selectedTheme:'default',unlockedThemes:['default'],lastDailyDate:'',dailyStreak:0,onboardingCompleted:false,tutorialCompleted:false,perfectGames:0,dailyMilestones:[],settings:{sound:true,music:true,vibration:true}});
export class PlayerManager {
  static readonly instance=new PlayerManager();data:PlayerData=defaults();lastRewards:RewardSnapshot={xp:0,coins:0,levelUp:false,achievements:[],levelRewardCoins:0};
  load(){try{const raw=globalThis.localStorage?.getItem(KEY);if(raw){const saved=JSON.parse(raw) as Partial<PlayerData>;this.data={...defaults(),...saved,settings:{...defaults().settings,...saved.settings}};}}catch{this.data=defaults();}}
  save(){try{globalThis.localStorage?.setItem(KEY,JSON.stringify(this.data));}catch{/* 微信适配层可替换存储 */}}
  get levelProgress(){return Math.min(1,this.data.experience/RewardSystem.xpForLevel(this.data.level));}
  setSkillLevel(level:SkillLevel){this.data.skillLevel=level;this.data.onboardingCompleted=true;this.save();}
  completeTutorial(){if(this.data.tutorialCompleted)return false;this.data.tutorialCompleted=true;this.data.coins+=30;if(!this.data.achievements.includes('tutorial'))this.data.achievements.push('tutorial');this.save();return true;}
  rewardTutorial(coins:number,xp:number){this.data.coins+=coins;this.data.experience+=xp;this.applyLevelUps();this.save();}
  spendCoins(amount:number){if(amount<0||this.data.coins<amount)return false;this.data.coins-=amount;this.save();return true;}
  completeLevel(mode:LevelMode,level:number,difficulty:Difficulty,elapsed:number,errors:number,hintsUsed:number){const result=LevelManager.instance.complete(mode,level,elapsed,errors,hintsUsed);this.data.completedGames++;if(errors===0)this.data.perfectGames++;this.data.coins+=result.coins;this.data.experience+=result.xp;const oldBest=this.data.bestTime[difficulty];if(!oldBest||elapsed<oldBest)this.data.bestTime[difficulty]=elapsed;this.data.history.unshift({difficulty,elapsed,errors,hintsUsed,date:new Date().toISOString(),levelMode:mode,levelNumber:level,stars:result.stars});this.data.history=this.data.history.slice(0,100);const upgrade=this.applyLevelUps();const achievements=AchievementSystem.evaluate(this.data,difficulty,elapsed,errors,hintsUsed,LevelManager.instance.getAllProgress());this.lastRewards={xp:result.xp,coins:result.coins,levelUp:upgrade.levelUp,newTitle:upgrade.newTitle,levelRewardCoins:upgrade.rewardCoins,achievements};this.save();return result;}
  completeGame(difficulty:Difficulty,elapsed:number,errors:number,daily=false){const reward=RewardSystem.game(difficulty,daily);this.data.completedGames++;if(errors===0)this.data.perfectGames++;this.data.experience+=reward.xp;this.data.coins+=reward.coins;const oldBest=this.data.bestTime[difficulty];if(!oldBest||elapsed<oldBest)this.data.bestTime[difficulty]=elapsed;this.data.history.unshift({difficulty,elapsed,errors,hintsUsed:0,date:new Date().toISOString(),daily});this.data.history=this.data.history.slice(0,100);const dailyReward=daily?this.updateDaily():undefined;const upgrade=this.applyLevelUps();const achievements=AchievementSystem.evaluate(this.data,difficulty,elapsed,errors,0,LevelManager.instance.getAllProgress());this.lastRewards={...reward,levelUp:upgrade.levelUp,newTitle:upgrade.newTitle,levelRewardCoins:upgrade.rewardCoins,achievements,dailyMilestone:dailyReward};this.save();return this.lastRewards;}
  private applyLevelUps(){const oldLevel=this.data.level;while(this.data.experience>=RewardSystem.xpForLevel(this.data.level)){this.data.experience-=RewardSystem.xpForLevel(this.data.level);this.data.level++;}const title=TitleManager.instance.getNewTitle(oldLevel,this.data.level);const rewardCoins=title?.unlockCoins??0;if(rewardCoins)this.data.coins+=rewardCoins;return{levelUp:this.data.level>oldLevel,newTitle:title?.title,rewardCoins};}
  private updateDaily(){const today=new Date();const key=this.dateKey(today);if(this.data.lastDailyDate===key)return undefined;const yesterday=new Date(today);yesterday.setDate(today.getDate()-1);this.data.dailyStreak=this.data.lastDailyDate===this.dateKey(yesterday)?this.data.dailyStreak+1:1;this.data.lastDailyDate=key;const milestone=`day${this.data.dailyStreak}`;if(this.data.dailyMilestones.includes(milestone))return undefined;let label:string|undefined;if(this.data.dailyStreak===1){this.data.coins+=10;label='Day 1 · 额外金币 +10';}else if(this.data.dailyStreak===3)label='Day 3 · 解锁星光头像框';else if(this.data.dailyStreak===7)label='Day 7 · 解锁特殊称号';else if(this.data.dailyStreak===30){ShopManager.instance.unlock('theme_streak30');label='Day 30 · 解锁晨曦限定主题';}if(label)this.data.dailyMilestones.push(milestone);return label;}
  private dateKey(d:Date){return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}
}
