import Phaser from 'phaser'; import type { Difficulty,LevelMode,Move } from '../types'; import type { GameThemeConfig } from '../data/themes'; import { SudokuGenerator } from '../sudoku/SudokuGenerator'; import { SudokuBoard,type CompletedUnit } from '../sudoku/SudokuBoard'; import { FONT,hex } from '../ui/theme'; import { addSurface } from '../ui/Surface'; import { IconButton } from '../ui/IconButton'; import { GameModal } from '../ui/GameModal'; import { getDifficulty,getLevelConfig } from '../data/levels'; import { getLevelMode } from '../data/difficulty'; import { PlayerManager } from '../systems/PlayerManager'; import { ShopManager } from '../systems/ShopManager'; import { ThemeManager } from '../systems/ThemeManager'; import { AudioManager } from '../systems/AudioManager';
interface NumberKey {container:Phaser.GameObjects.Container;face:Phaser.GameObjects.Graphics;text:Phaser.GameObjects.Text;}
const GAME_CONTROLS={toolbar:{startX:58,y:525,gapX:102},keyboard:{startX:103,startY:610,width:88,height:44,gapX:19,gapY:14}} as const;
export class GameScene extends Phaser.Scene {
  private board!:SudokuBoard;private solution!:number[][];private difficulty:Difficulty='easy';private levelMode?:LevelMode;private levelNumber=1;private daily=false;private elapsed=0;private errors=0;private hintsUsed=0;private noteMode=false;private paused=false;private finishing=false;private undo:Move[]=[];private timerText!:Phaser.GameObjects.Text;private errorText!:Phaser.GameObjects.Text;private noteButton!:IconButton;private hintButton!:IconButton;private numberKeys:Record<number,NumberKey>={};private timerEvent?:Phaser.Time.TimerEvent;private pending:Phaser.Time.TimerEvent[]=[];private initialData!:Readonly<{difficulty:Difficulty;daily:boolean;levelMode?:LevelMode;levelNumber:number}>;
  constructor(){super('Game');}
  init(data:{difficulty?:Difficulty;daily?:boolean;levelMode?:LevelMode;levelNumber?:number}){this.levelMode=data.levelMode;this.levelNumber=data.levelNumber??1;const config=this.levelMode?getLevelConfig(this.levelMode,this.levelNumber):undefined;this.difficulty=config?.generatorDifficulty??data.difficulty??'easy';this.daily=!!data.daily;this.elapsed=0;this.errors=0;this.hintsUsed=0;this.undo=[];this.noteMode=false;this.paused=false;this.finishing=false;this.numberKeys={};this.pending=[];this.initialData={difficulty:this.difficulty,daily:this.daily,levelMode:this.levelMode,levelNumber:this.levelNumber};}
  create(){const theme=ThemeManager.instance.current;this.cameras.main.setBackgroundColor(theme.background);const modeLabel=this.daily?'每日挑战':this.levelMode?getLevelMode(this.levelMode).name:`${getDifficulty(this.difficulty).name}模式`;const title=this.daily?'今日数独':this.levelMode?`第 ${this.levelNumber} 关`:'经典数独';addSurface(this,210,48,392,76,{radius:20,color:theme.panel,border:theme.accentSoft});this.add.text(28,47,'‹',{fontFamily:FONT,fontSize:'38px',color:hex(theme.givenNumber)}).setOrigin(.5).setInteractive({useHandCursor:true}).on('pointerup',()=>this.confirmExit());this.add.text(72,29,title,{fontFamily:FONT,fontSize:'18px',fontStyle:'bold',color:hex(theme.givenNumber)});this.add.text(72,53,modeLabel,{fontFamily:FONT,fontSize:'10px',color:hex(theme.noteNumber)});this.timerText=this.add.text(294,27,'00:00',{fontFamily:FONT,fontSize:'14px',fontStyle:'bold',color:hex(theme.givenNumber)}).setOrigin(.5,0);this.errorText=this.add.text(294,52,'♥ ♥ ♥',{fontFamily:FONT,fontSize:'12px',color:hex(theme.danger)}).setOrigin(.5,0);this.add.circle(374,48,22,theme.accent,.1).setInteractive({useHandCursor:true}).on('pointerup',()=>this.showPause());this.add.text(374,48,'Ⅱ',{fontFamily:FONT,fontSize:'17px',fontStyle:'bold',color:hex(theme.accent)}).setOrigin(.5);
    const date=new Date(),levelConfig=this.levelMode?getLevelConfig(this.levelMode,this.levelNumber):undefined,seed=this.daily?Number(`${date.getFullYear()}${date.getMonth()+1}${date.getDate()}`):levelConfig?.seed;const generated=SudokuGenerator.generate(this.difficulty,seed,levelConfig?.clues,levelConfig?.removalPattern);this.solution=generated.solution;this.board=new SudokuBoard(this,21,96,generated.puzzle,{...theme,playerNumber:ThemeManager.instance.playerNumberColor});this.board.onSelect=(row,col)=>this.updateNumberKeys(this.board.values[row][col]||undefined);
    const accent=theme.accent,toolX=(index:number)=>GAME_CONTROLS.toolbar.startX+index*GAME_CONTROLS.toolbar.gapX;new IconButton(this,toolX(0),GAME_CONTROLS.toolbar.y,'↶','撤销',accent,()=>this.doUndo());new IconButton(this,toolX(1),GAME_CONTROLS.toolbar.y,'⌫','擦除',accent,()=>this.erase());this.noteButton=new IconButton(this,toolX(2),GAME_CONTROLS.toolbar.y,'✎','笔记',accent,()=>this.toggleNote());this.hintButton=new IconButton(this,toolX(3),GAME_CONTROLS.toolbar.y,'✦',`提示 ×${ShopManager.instance.data.hintTickets}`,accent,()=>this.hint());
    for(let number=1;number<=9;number++)this.createNumberKey(number,theme);this.updateNumberKeys();this.timerEvent=this.time.addEvent({delay:1000,loop:true,callback:()=>{if(!this.paused&&!this.finishing){this.elapsed++;this.timerText.setText(this.format(this.elapsed));}}});this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.cleanup());}
  private createNumberKey(number:number,theme:GameThemeConfig){const layout=GAME_CONTROLS.keyboard,col=(number-1)%3,row=Math.floor((number-1)/3),x=layout.startX+col*(layout.width+layout.gapX),y=layout.startY+row*(layout.height+layout.gapY),container=this.add.container(x,y),face=this.add.graphics(),text=this.add.text(0,0,String(number),{fontFamily:FONT,fontSize:'22px',fontStyle:'bold',color:hex(theme.givenNumber),align:'center'}).setOrigin(.5);container.add([face,text]);container.setSize(layout.width,layout.height).setInteractive({useHandCursor:true});container.on('pointerdown',()=>this.tweens.add({targets:container,scale:.94,duration:55}));container.on('pointerup',()=>this.tweens.add({targets:container,scale:1,duration:120,ease:'Back.easeOut',onComplete:()=>this.inputNumber(number)}));this.numberKeys[number]={container,face,text};}
  private drawNumberKey(number:number,selected=false){const theme=ThemeManager.instance.current,key=this.numberKeys[number],layout=GAME_CONTROLS.keyboard,complete=this.board.countValue(number)>=9;key.face.clear();key.face.fillStyle(selected?theme.accent:theme.keyboard,1);key.face.fillRoundedRect(-layout.width/2,-layout.height/2,layout.width,layout.height,14);key.face.lineStyle(1,selected?theme.accent:theme.grid,.75);key.face.strokeRoundedRect(-layout.width/2,-layout.height/2,layout.width,layout.height,14);key.text.setColor(hex(selected?0xffffff:complete?theme.noteNumber:theme.givenNumber));key.container.setAlpha(complete ? .38 : 1);key.container.disableInteractive();if(!complete)key.container.setInteractive({useHandCursor:true});}
  private updateNumberKeys(selected?:number){for(let number=1;number<=9;number++)this.drawNumberKey(number,selected===number);}
  private inputNumber(number:number){const {row,col}=this.board.selected;if(row<0||this.board.isGiven(row,col)||this.paused||this.finishing||this.board.countValue(number)>=9)return;AudioManager.instance.play(this,'click');this.updateNumberKeys(number);const previous=this.board.values[row][col],previousNotes=[...this.board.notes[row][col]];if(this.noteMode){const next=previousNotes.includes(number)?previousNotes.filter(value=>value!==number):[...previousNotes,number].sort();this.undo.push({row,col,previous,value:0,previousNotes});this.board.setNotes(row,col,next);return;}const before=this.board.getCompletedUnits();this.undo.push({row,col,previous,value:number,previousNotes});if(number!==this.solution[row][col]){this.errors++;AudioManager.instance.play(this,'wrong');this.board.setValue(row,col,number,true);this.board.shakeCell(row,col);this.errorText.setText(Array.from({length:3},(_,i)=>i<this.errors?'♡':'♥').join(' '));this.pending.push(this.time.delayedCall(480,()=>{this.board.setValue(row,col,0);this.board.clearWrong();this.updateNumberKeys();}));if(this.errors>=3)this.pending.push(this.time.delayedCall(560,()=>this.finish(false)));return;}AudioManager.instance.play(this,'correct');this.board.setValue(row,col,number);this.board.animateValue(row,col);this.clearPeerNotes(row,col,number);this.checkCompletedUnits(before);this.updateNumberKeys(number);if(this.board.isComplete())this.completeAnimation();}
  private checkCompletedUnits(before:Set<CompletedUnit>){const after=this.board.getCompletedUnits(),added=[...after].filter(unit=>!before.has(unit));if(added.length){AudioManager.instance.play(this,'unitComplete');this.board.flashUnits(added);}}
  private clearPeerNotes(row:number,col:number,number:number){for(let i=0;i<9;i++){this.board.notes[row][i]=this.board.notes[row][i].filter(value=>value!==number);this.board.notes[i][col]=this.board.notes[i][col].filter(value=>value!==number);}this.board.refresh();}
  private erase(){const {row,col}=this.board.selected;if(row<0||this.board.isGiven(row,col)||this.paused)return;AudioManager.instance.play(this,'click');this.undo.push({row,col,previous:this.board.values[row][col],value:0,previousNotes:[...this.board.notes[row][col]]});this.board.setValue(row,col,0);this.updateNumberKeys();}
  private doUndo(){if(this.paused)return;const move=this.undo.pop();if(!move)return;AudioManager.instance.play(this,'click');this.board.values[move.row][move.col]=move.previous;this.board.notes[move.row][move.col]=move.previousNotes;this.board.select(move.row,move.col);this.updateNumberKeys();}
  private toggleNote(){if(this.paused)return;AudioManager.instance.play(this,'click');this.noteMode=!this.noteMode;this.noteButton.setHighlighted(this.noteMode,ThemeManager.instance.current.accent).setLabel(this.noteMode?'笔记 ON':'笔记');}
  private hint(){if(this.paused)return;const {row,col}=this.board.selected;if(row<0||this.board.isGiven(row,col))return;if(ShopManager.instance.data.hintTickets<=0){this.paused=true;new GameModal(this,{title:'提示券不足',message:'前往商城购买提示券后即可使用提示。',primaryLabel:'前往商城',secondaryLabel:'继续游戏',onPrimary:()=>this.scene.start('Shop'),onSecondary:()=>{this.paused=false;}});return;}ShopManager.instance.useHintTicket();this.hintsUsed++;this.hintButton.setLabel(`提示 ×${ShopManager.instance.data.hintTickets}`);const before=this.board.getCompletedUnits();this.board.setValue(row,col,this.solution[row][col]);this.board.animateValue(row,col);this.checkCompletedUnits(before);this.updateNumberKeys(this.solution[row][col]);if(this.board.isComplete())this.completeAnimation();}
  private showPause(){if(this.paused||this.finishing)return;this.paused=true;this.board.setInputEnabled(false);AudioManager.instance.play(this,'click');new GameModal(this,{title:'游戏暂停',message:'计时已经暂停，可以随时继续。',primaryLabel:'继续游戏',secondaryLabel:'重新开始',tertiaryLabel:'返回首页',onPrimary:()=>this.resume(),onSecondary:()=>this.confirmRestart(),onTertiary:()=>this.confirmExit(true)});}
  private resume(){this.paused=false;this.board.setInputEnabled(true);}
  private confirmRestart(){this.paused=true;new GameModal(this,{title:'重新开始本关？',message:'当前填写内容将被清空，题目不会改变。',primaryLabel:'重新开始',secondaryLabel:'继续游戏',onPrimary:()=>this.scene.restart(this.initialData),onSecondary:()=>this.resume()});}
  private confirmExit(fromPause=false){if(this.finishing)return;this.paused=true;this.board?.setInputEnabled(false);new GameModal(this,{title:'退出当前关卡？',message:'当前关卡不会被标记完成，题目和关卡进度保持不变。',primaryLabel:'退出到首页',secondaryLabel:'继续游戏',onPrimary:()=>this.scene.start('Home'),onSecondary:()=>this.resume()});if(fromPause)this.board?.setInputEnabled(false);}
  private completeAnimation(){if(this.finishing)return;this.finishing=true;this.paused=true;this.board.setInputEnabled(false);AudioManager.instance.play(this,'levelComplete');for(let box=0;box<9;box++)this.pending.push(this.time.delayedCall(box*45,()=>this.board.flashUnits([`box-${box}`])));this.pending.push(this.time.delayedCall(560,()=>this.finish(true)));}
  private finish(success:boolean){if(success){if(this.levelMode)PlayerManager.instance.completeLevel(this.levelMode,this.levelNumber,this.difficulty,this.elapsed,this.errors,this.hintsUsed);else PlayerManager.instance.completeGame(this.difficulty,this.elapsed,this.errors,this.daily);}this.scene.start('Result',{success,difficulty:this.difficulty,elapsed:this.elapsed,errors:this.errors,hintsUsed:this.hintsUsed,daily:this.daily,levelMode:this.levelMode,levelNumber:this.levelNumber});}
  private cleanup(){this.timerEvent?.remove(false);for(const event of this.pending)event.remove(false);this.pending=[];this.tweens.killAll();}
  private format(seconds:number){return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
}
