import Phaser from 'phaser'; import type { Difficulty,LevelMode } from '../types'; import { addBackground } from '../ui/layout'; import { addSurface } from '../ui/Surface'; import { COLORS,FONT,hex } from '../ui/theme'; import { Button } from '../ui/Button'; import { PlayerManager } from '../systems/PlayerManager'; import { LevelManager } from '../systems/LevelManager'; import { RewardSystem } from '../systems/RewardSystem'; import { AudioManager } from '../systems/AudioManager'; import { getDifficulty } from '../data/levels'; import { getLevelMode } from '../data/difficulty'; import { ACHIEVEMENTS } from '../data/achievements';
export class ResultScene extends Phaser.Scene {
  constructor(){super('Result')}
  create(data:{success:boolean;difficulty:Difficulty;elapsed:number;errors:number;hintsUsed?:number;daily:boolean;levelMode?:LevelMode;levelNumber?:number}){addBackground(this);const reward=PlayerManager.instance.lastRewards;const levelResult=data.levelMode?LevelManager.instance.lastResult:undefined;this.add.circle(210,135,62,data.success?COLORS.secondary:COLORS.danger,.12);this.add.text(210,135,data.success?'✓':'×',{fontFamily:FONT,fontSize:'60px',fontStyle:'bold',color:data.success?hex(COLORS.secondary):hex(COLORS.danger)}).setOrigin(.5);
    const heading=data.success&&data.levelMode?`恭喜完成第 ${data.levelNumber} 关`:data.success?'挑战完成！':'本局结束';this.add.text(210,225,heading,{fontFamily:FONT,fontSize:'27px',fontStyle:'bold',color:hex(COLORS.text)}).setOrigin(.5);this.add.text(210,266,data.levelMode?getLevelMode(data.levelMode).name:data.daily?'每日挑战':`${getDifficulty(data.difficulty).name}模式`,{fontFamily:FONT,fontSize:'13px',color:hex(COLORS.muted)}).setOrigin(.5);
    if(data.success&&levelResult)this.add.text(210,310,'★'.repeat(levelResult.stars)+'☆'.repeat(3-levelResult.stars),{fontFamily:FONT,fontSize:'39px',color:hex(COLORS.gold),letterSpacing:6}).setOrigin(.5);
    const statsLeft=30,statsWidth=360,statsColumnWidth=statsWidth/3;addSurface(this,210,390,statsWidth,112,{radius:20});['用时','错误','提示'].forEach((label,index)=>this.stat(statsLeft+(index+.5)*statsColumnWidth,366,label,[this.format(data.elapsed),String(data.errors),String(data.hintsUsed??0)][index]));
    if(data.success){AudioManager.instance.play(this,'coin');const rewardRow=this.add.container(210,472),coinText=this.add.text(-98,0,'金币  +0',{fontFamily:FONT,fontSize:'16px',fontStyle:'bold',color:hex(COLORS.gold)}).setOrigin(.5),xpText=this.add.text(98,0,`经验  +${reward.xp}`,{fontFamily:FONT,fontSize:'16px',fontStyle:'bold',color:hex(COLORS.primary)}).setOrigin(.5);rewardRow.add([coinText,xpText]);this.tweens.addCounter({from:0,to:reward.coins,duration:600,onUpdate:tween=>coinText.setText(`金币  +${Math.floor(tween.getValue()??0)}`)});if(levelResult&&(levelResult.perfectBonus>0||levelResult.noHintBonus>0))this.add.text(210,504,`${levelResult.perfectBonus?`无错误 +${levelResult.perfectBonus} 金币  `:''}${levelResult.noHintBonus?`无提示 +${levelResult.noHintBonus} 金币`:''}`,{fontFamily:FONT,fontSize:'11px',color:hex(COLORS.secondary),align:'center'}).setOrigin(.5);const hasLevelNotice=Boolean(reward.newTitle||reward.levelUp);if(reward.newTitle){AudioManager.instance.play(this,'levelUp');const title=this.add.text(210,536,`升级成功！  解锁称号：${reward.newTitle}\n升级奖励 +${reward.levelRewardCoins} 金币`,{fontFamily:FONT,fontSize:'12px',fontStyle:'bold',align:'center',lineSpacing:5,color:hex(COLORS.primary)}).setOrigin(.5);this.tweens.add({targets:title,scale:{from:.7,to:1},alpha:{from:0,to:1},duration:480,ease:'Back.easeOut'});}else if(reward.levelUp)this.add.text(210,536,'升级成功！',{fontFamily:FONT,fontSize:'13px',fontStyle:'bold',color:hex(COLORS.primary)}).setOrigin(.5);const noticeY=hasLevelNotice?568:540;if(reward.dailyMilestone)this.add.text(210,noticeY,reward.dailyMilestone,{fontFamily:FONT,fontSize:'11px',fontStyle:'bold',color:hex(COLORS.gold)}).setOrigin(.5);else if(reward.achievements.length){const a=ACHIEVEMENTS.find(x=>x.id===reward.achievements[0]);this.add.text(210,noticeY,`新成就：${a?.icon} ${a?.name}`,{fontFamily:FONT,fontSize:'11px',color:hex(COLORS.secondary)}).setOrigin(.5);}const xpY=596;this.add.rectangle(58,xpY,246,7,0xe4e5ed).setOrigin(0,.5);const xpBar=this.add.rectangle(58,xpY,0,7,COLORS.primary).setOrigin(0,.5);this.tweens.add({targets:xpBar,width:246*PlayerManager.instance.levelProgress,duration:800,ease:'Cubic.easeOut'});this.add.text(362,xpY,`${PlayerManager.instance.data.experience}/${RewardSystem.xpForLevel(PlayerManager.instance.data.level)} XP`,{fontFamily:FONT,fontSize:'9px',color:hex(COLORS.muted),align:'right'}).setOrigin(1,.5);}
    const primaryLabel=data.success&&data.levelMode&&data.levelNumber!==100?'下一关':data.success?'再来一局':'重新挑战';new Button(this,210,650,330,58,primaryLabel,()=>this.next(data));new Button(this,210,722,330,48,'返回首页',()=>this.scene.start('Home'),COLORS.card);
  }
  private stat(x:number,y:number,label:string,value:string){this.add.text(x,y,label,{fontFamily:FONT,fontSize:'11px',color:hex(COLORS.muted)}).setOrigin(.5);this.add.text(x,y+31,value,{fontFamily:FONT,fontSize:'19px',fontStyle:'bold',color:hex(COLORS.text)}).setOrigin(.5);}
  private next(data:{difficulty:Difficulty;daily:boolean;levelMode?:LevelMode;levelNumber?:number}){if(data.levelMode){const next=LevelManager.instance.getProgress(data.levelMode).currentLevel;this.scene.start('Game',{levelMode:data.levelMode,levelNumber:next});}else this.scene.start('Game',{difficulty:data.difficulty,daily:data.daily});}
  private format(s:number){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
}
